name: Paradigm Shift Apparel
favicon: null
layout_spectrum: 0.15822695149108768
typography_spectrum: 0.8306897336151451
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.3567642879206687
  lightness: 0.43984707864001393
  saturation: 0.3158956978004426
  rhythmicContrast: 0.5717528744135052
purpose: []
