name: Paradigm Shift Apparel
favicon: null
layout_spectrum: 1
typography_spectrum: 0.09696
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#fefefe'
    - '#9b6086'
    - '#3f11a1'
    - '#51c3e8'
  brandStrength: 0.75
  lightness: 0.0625
  saturation: 0
  rhythmicContrast: 1
purpose: []
